// Code generated by mockery v2.10.0. DO NOT EDIT.

package postgresmocks

import (
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"
)

// ConnManager is an autogenerated mock type for the connManager type
type ConnManager struct {
	mock.Mock
}

type ConnManager_Expecter struct {
	mock *mock.Mock
}

func (_m *ConnManager) EXPECT() *ConnManager_Expecter {
	return &ConnManager_Expecter{mock: &_m.Mock}
}

// GetConnection provides a mock function with given fields:
func (_m *ConnManager) GetConnection() (*sqlx.DB, error) {
	ret := _m.Called()

	var r0 *sqlx.DB
	if rf, ok := ret.Get(0).(func() *sqlx.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlx.DB)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConnManager_GetConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnection'
type ConnManager_GetConnection_Call struct {
	*mock.Call
}

// GetConnection is a helper method to define mock.On call
func (_e *ConnManager_Expecter) GetConnection() *ConnManager_GetConnection_Call {
	return &ConnManager_GetConnection_Call{Call: _e.mock.On("GetConnection")}
}

func (_c *ConnManager_GetConnection_Call) Run(run func()) *ConnManager_GetConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConnManager_GetConnection_Call) Return(_a0 *sqlx.DB, _a1 error) *ConnManager_GetConnection_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}
