import Base from './Base'

function Settings() {
    return (
        <Base>
            <h3>Settings</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vel tempus odio, nec tempor purus. Vivamus consequat eros risus, vitae sagittis lacus luctus eget. Sed quis turpis consectetur, aliquet neque in, tincidunt nisi. Integer malesuada, metus consequat porttitor rhoncus, nulla risus hendrerit ex, convallis consequat diam lectus ac arcu. Nulla auctor eros ac hendrerit faucibus. In porta diam ut vulputate interdum. Suspendisse potenti. Phasellus mollis, ipsum nec bibendum vestibulum, tellus metus dignissim tellus, vel rutrum velit eros a est. Phasellus quis sapien orci.</p>

            <p>Quisque ultrices rhoncus gravida. Suspendisse imperdiet eros vel arcu malesuada sodales vel nec diam. Ut quis ligula posuere, ullamcorper diam at, congue purus. Etiam condimentum consequat odio, et aliquam magna hendrerit et. Mauris vestibulum rutrum imperdiet. Vivamus suscipit vel sapien nec iaculis. Aenean sit amet felis eros. Nulla hendrerit, elit sit amet vestibulum venenatis, orci leo consequat purus, sit amet posuere odio tortor eget enim. Etiam vel lobortis ante. Morbi tincidunt, nulla vel auctor tincidunt, ipsum magna cursus dui, at molestie justo augue id nunc.</p>

            <p>Proin mauris ante, venenatis ac lacus vel, ultrices auctor elit. Aliquam euismod congue metus, ut molestie nunc dignissim sit amet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin ut pellentesque tellus. Duis lobortis justo eu aliquet efficitur. Fusce sit amet felis ligula. Suspendisse pretium elit vel purus auctor, vel tincidunt erat consequat.</p>

            <p>Phasellus ut feugiat libero. Sed et purus metus. Integer eu est molestie, bibendum odio nec, pharetra mauris. Nullam nisl sapien, accumsan vel lacinia eu, dictum id urna. Donec sem diam, posuere sit amet lacus vel, pharetra convallis nulla. Morbi ultrices vehicula mauris, a congue lorem placerat dignissim. Pellentesque sagittis mattis euismod. Sed blandit pellentesque purus, at mollis sem venenatis in. Maecenas sed erat id velit mollis malesuada vitae vel risus. Vivamus condimentum ligula massa, at consectetur lectus fringilla id. Integer volutpat eleifend neque sed hendrerit. Vivamus laoreet eros non metus facilisis, sed efficitur purus dignissim.</p>

            <p>Etiam ut purus vitae augue varius congue id luctus augue. Sed suscipit efficitur ex a condimentum. Proin sit amet dignissim ex. Suspendisse potenti. Duis sed sem sit amet est placerat lobortis. Vivamus nunc nisi, commodo et libero sit amet, iaculis vehicula urna. Aenean erat erat, tempor ac sem non, pretium ultrices augue. Curabitur vitae rutrum lacus. Vivamus in luctus sapien. Phasellus imperdiet augue at lectus sollicitudin, eget pulvinar lacus pellentesque. Quisque quis porta tortor. Phasellus ullamcorper, nisi nec ultrices accumsan, tellus turpis sagittis nunc, quis molestie enim elit eget est.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vel tempus odio, nec tempor purus. Vivamus consequat eros risus, vitae sagittis lacus luctus eget. Sed quis turpis consectetur, aliquet neque in, tincidunt nisi. Integer malesuada, metus consequat porttitor rhoncus, nulla risus hendrerit ex, convallis consequat diam lectus ac arcu. Nulla auctor eros ac hendrerit faucibus. In porta diam ut vulputate interdum. Suspendisse potenti. Phasellus mollis, ipsum nec bibendum vestibulum, tellus metus dignissim tellus, vel rutrum velit eros a est. Phasellus quis sapien orci.</p>

            <p>Quisque ultrices rhoncus gravida. Suspendisse imperdiet eros vel arcu malesuada sodales vel nec diam. Ut quis ligula posuere, ullamcorper diam at, congue purus. Etiam condimentum consequat odio, et aliquam magna hendrerit et. Mauris vestibulum rutrum imperdiet. Vivamus suscipit vel sapien nec iaculis. Aenean sit amet felis eros. Nulla hendrerit, elit sit amet vestibulum venenatis, orci leo consequat purus, sit amet posuere odio tortor eget enim. Etiam vel lobortis ante. Morbi tincidunt, nulla vel auctor tincidunt, ipsum magna cursus dui, at molestie justo augue id nunc.</p>

            <p>Proin mauris ante, venenatis ac lacus vel, ultrices auctor elit. Aliquam euismod congue metus, ut molestie nunc dignissim sit amet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin ut pellentesque tellus. Duis lobortis justo eu aliquet efficitur. Fusce sit amet felis ligula. Suspendisse pretium elit vel purus auctor, vel tincidunt erat consequat.</p>

            <p>Phasellus ut feugiat libero. Sed et purus metus. Integer eu est molestie, bibendum odio nec, pharetra mauris. Nullam nisl sapien, accumsan vel lacinia eu, dictum id urna. Donec sem diam, posuere sit amet lacus vel, pharetra convallis nulla. Morbi ultrices vehicula mauris, a congue lorem placerat dignissim. Pellentesque sagittis mattis euismod. Sed blandit pellentesque purus, at mollis sem venenatis in. Maecenas sed erat id velit mollis malesuada vitae vel risus. Vivamus condimentum ligula massa, at consectetur lectus fringilla id. Integer volutpat eleifend neque sed hendrerit. Vivamus laoreet eros non metus facilisis, sed efficitur purus dignissim.</p>

            <p>Etiam ut purus vitae augue varius congue id luctus augue. Sed suscipit efficitur ex a condimentum. Proin sit amet dignissim ex. Suspendisse potenti. Duis sed sem sit amet est placerat lobortis. Vivamus nunc nisi, commodo et libero sit amet, iaculis vehicula urna. Aenean erat erat, tempor ac sem non, pretium ultrices augue. Curabitur vitae rutrum lacus. Vivamus in luctus sapien. Phasellus imperdiet augue at lectus sollicitudin, eget pulvinar lacus pellentesque. Quisque quis porta tortor. Phasellus ullamcorper, nisi nec ultrices accumsan, tellus turpis sagittis nunc, quis molestie enim elit eget est.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vel tempus odio, nec tempor purus. Vivamus consequat eros risus, vitae sagittis lacus luctus eget. Sed quis turpis consectetur, aliquet neque in, tincidunt nisi. Integer malesuada, metus consequat porttitor rhoncus, nulla risus hendrerit ex, convallis consequat diam lectus ac arcu. Nulla auctor eros ac hendrerit faucibus. In porta diam ut vulputate interdum. Suspendisse potenti. Phasellus mollis, ipsum nec bibendum vestibulum, tellus metus dignissim tellus, vel rutrum velit eros a est. Phasellus quis sapien orci.</p>

            <p>Quisque ultrices rhoncus gravida. Suspendisse imperdiet eros vel arcu malesuada sodales vel nec diam. Ut quis ligula posuere, ullamcorper diam at, congue purus. Etiam condimentum consequat odio, et aliquam magna hendrerit et. Mauris vestibulum rutrum imperdiet. Vivamus suscipit vel sapien nec iaculis. Aenean sit amet felis eros. Nulla hendrerit, elit sit amet vestibulum venenatis, orci leo consequat purus, sit amet posuere odio tortor eget enim. Etiam vel lobortis ante. Morbi tincidunt, nulla vel auctor tincidunt, ipsum magna cursus dui, at molestie justo augue id nunc.</p>

            <p>Proin mauris ante, venenatis ac lacus vel, ultrices auctor elit. Aliquam euismod congue metus, ut molestie nunc dignissim sit amet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin ut pellentesque tellus. Duis lobortis justo eu aliquet efficitur. Fusce sit amet felis ligula. Suspendisse pretium elit vel purus auctor, vel tincidunt erat consequat.</p>

            <p>Phasellus ut feugiat libero. Sed et purus metus. Integer eu est molestie, bibendum odio nec, pharetra mauris. Nullam nisl sapien, accumsan vel lacinia eu, dictum id urna. Donec sem diam, posuere sit amet lacus vel, pharetra convallis nulla. Morbi ultrices vehicula mauris, a congue lorem placerat dignissim. Pellentesque sagittis mattis euismod. Sed blandit pellentesque purus, at mollis sem venenatis in. Maecenas sed erat id velit mollis malesuada vitae vel risus. Vivamus condimentum ligula massa, at consectetur lectus fringilla id. Integer volutpat eleifend neque sed hendrerit. Vivamus laoreet eros non metus facilisis, sed efficitur purus dignissim.</p>

            <p>Etiam ut purus vitae augue varius congue id luctus augue. Sed suscipit efficitur ex a condimentum. Proin sit amet dignissim ex. Suspendisse potenti. Duis sed sem sit amet est placerat lobortis. Vivamus nunc nisi, commodo et libero sit amet, iaculis vehicula urna. Aenean erat erat, tempor ac sem non, pretium ultrices augue. Curabitur vitae rutrum lacus. Vivamus in luctus sapien. Phasellus imperdiet augue at lectus sollicitudin, eget pulvinar lacus pellentesque. Quisque quis porta tortor. Phasellus ullamcorper, nisi nec ultrices accumsan, tellus turpis sagittis nunc, quis molestie enim elit eget est.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vel tempus odio, nec tempor purus. Vivamus consequat eros risus, vitae sagittis lacus luctus eget. Sed quis turpis consectetur, aliquet neque in, tincidunt nisi. Integer malesuada, metus consequat porttitor rhoncus, nulla risus hendrerit ex, convallis consequat diam lectus ac arcu. Nulla auctor eros ac hendrerit faucibus. In porta diam ut vulputate interdum. Suspendisse potenti. Phasellus mollis, ipsum nec bibendum vestibulum, tellus metus dignissim tellus, vel rutrum velit eros a est. Phasellus quis sapien orci.</p>

            <p>Quisque ultrices rhoncus gravida. Suspendisse imperdiet eros vel arcu malesuada sodales vel nec diam. Ut quis ligula posuere, ullamcorper diam at, congue purus. Etiam condimentum consequat odio, et aliquam magna hendrerit et. Mauris vestibulum rutrum imperdiet. Vivamus suscipit vel sapien nec iaculis. Aenean sit amet felis eros. Nulla hendrerit, elit sit amet vestibulum venenatis, orci leo consequat purus, sit amet posuere odio tortor eget enim. Etiam vel lobortis ante. Morbi tincidunt, nulla vel auctor tincidunt, ipsum magna cursus dui, at molestie justo augue id nunc.</p>

            <p>Proin mauris ante, venenatis ac lacus vel, ultrices auctor elit. Aliquam euismod congue metus, ut molestie nunc dignissim sit amet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin ut pellentesque tellus. Duis lobortis justo eu aliquet efficitur. Fusce sit amet felis ligula. Suspendisse pretium elit vel purus auctor, vel tincidunt erat consequat.</p>

            <p>Phasellus ut feugiat libero. Sed et purus metus. Integer eu est molestie, bibendum odio nec, pharetra mauris. Nullam nisl sapien, accumsan vel lacinia eu, dictum id urna. Donec sem diam, posuere sit amet lacus vel, pharetra convallis nulla. Morbi ultrices vehicula mauris, a congue lorem placerat dignissim. Pellentesque sagittis mattis euismod. Sed blandit pellentesque purus, at mollis sem venenatis in. Maecenas sed erat id velit mollis malesuada vitae vel risus. Vivamus condimentum ligula massa, at consectetur lectus fringilla id. Integer volutpat eleifend neque sed hendrerit. Vivamus laoreet eros non metus facilisis, sed efficitur purus dignissim.</p>

            <p>Etiam ut purus vitae augue varius congue id luctus augue. Sed suscipit efficitur ex a condimentum. Proin sit amet dignissim ex. Suspendisse potenti. Duis sed sem sit amet est placerat lobortis. Vivamus nunc nisi, commodo et libero sit amet, iaculis vehicula urna. Aenean erat erat, tempor ac sem non, pretium ultrices augue. Curabitur vitae rutrum lacus. Vivamus in luctus sapien. Phasellus imperdiet augue at lectus sollicitudin, eget pulvinar lacus pellentesque. Quisque quis porta tortor. Phasellus ullamcorper, nisi nec ultrices accumsan, tellus turpis sagittis nunc, quis molestie enim elit eget est.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vel tempus odio, nec tempor purus. Vivamus consequat eros risus, vitae sagittis lacus luctus eget. Sed quis turpis consectetur, aliquet neque in, tincidunt nisi. Integer malesuada, metus consequat porttitor rhoncus, nulla risus hendrerit ex, convallis consequat diam lectus ac arcu. Nulla auctor eros ac hendrerit faucibus. In porta diam ut vulputate interdum. Suspendisse potenti. Phasellus mollis, ipsum nec bibendum vestibulum, tellus metus dignissim tellus, vel rutrum velit eros a est. Phasellus quis sapien orci.</p>

            <p>Quisque ultrices rhoncus gravida. Suspendisse imperdiet eros vel arcu malesuada sodales vel nec diam. Ut quis ligula posuere, ullamcorper diam at, congue purus. Etiam condimentum consequat odio, et aliquam magna hendrerit et. Mauris vestibulum rutrum imperdiet. Vivamus suscipit vel sapien nec iaculis. Aenean sit amet felis eros. Nulla hendrerit, elit sit amet vestibulum venenatis, orci leo consequat purus, sit amet posuere odio tortor eget enim. Etiam vel lobortis ante. Morbi tincidunt, nulla vel auctor tincidunt, ipsum magna cursus dui, at molestie justo augue id nunc.</p>

            <p>Proin mauris ante, venenatis ac lacus vel, ultrices auctor elit. Aliquam euismod congue metus, ut molestie nunc dignissim sit amet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin ut pellentesque tellus. Duis lobortis justo eu aliquet efficitur. Fusce sit amet felis ligula. Suspendisse pretium elit vel purus auctor, vel tincidunt erat consequat.</p>

            <p>Phasellus ut feugiat libero. Sed et purus metus. Integer eu est molestie, bibendum odio nec, pharetra mauris. Nullam nisl sapien, accumsan vel lacinia eu, dictum id urna. Donec sem diam, posuere sit amet lacus vel, pharetra convallis nulla. Morbi ultrices vehicula mauris, a congue lorem placerat dignissim. Pellentesque sagittis mattis euismod. Sed blandit pellentesque purus, at mollis sem venenatis in. Maecenas sed erat id velit mollis malesuada vitae vel risus. Vivamus condimentum ligula massa, at consectetur lectus fringilla id. Integer volutpat eleifend neque sed hendrerit. Vivamus laoreet eros non metus facilisis, sed efficitur purus dignissim.</p>

            <p>Etiam ut purus vitae augue varius congue id luctus augue. Sed suscipit efficitur ex a condimentum. Proin sit amet dignissim ex. Suspendisse potenti. Duis sed sem sit amet est placerat lobortis. Vivamus nunc nisi, commodo et libero sit amet, iaculis vehicula urna. Aenean erat erat, tempor ac sem non, pretium ultrices augue. Curabitur vitae rutrum lacus. Vivamus in luctus sapien. Phasellus imperdiet augue at lectus sollicitudin, eget pulvinar lacus pellentesque. Quisque quis porta tortor. Phasellus ullamcorper, nisi nec ultrices accumsan, tellus turpis sagittis nunc, quis molestie enim elit eget est.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi vel tempus odio, nec tempor purus. Vivamus consequat eros risus, vitae sagittis lacus luctus eget. Sed quis turpis consectetur, aliquet neque in, tincidunt nisi. Integer malesuada, metus consequat porttitor rhoncus, nulla risus hendrerit ex, convallis consequat diam lectus ac arcu. Nulla auctor eros ac hendrerit faucibus. In porta diam ut vulputate interdum. Suspendisse potenti. Phasellus mollis, ipsum nec bibendum vestibulum, tellus metus dignissim tellus, vel rutrum velit eros a est. Phasellus quis sapien orci.</p>

            <p>Quisque ultrices rhoncus gravida. Suspendisse imperdiet eros vel arcu malesuada sodales vel nec diam. Ut quis ligula posuere, ullamcorper diam at, congue purus. Etiam condimentum consequat odio, et aliquam magna hendrerit et. Mauris vestibulum rutrum imperdiet. Vivamus suscipit vel sapien nec iaculis. Aenean sit amet felis eros. Nulla hendrerit, elit sit amet vestibulum venenatis, orci leo consequat purus, sit amet posuere odio tortor eget enim. Etiam vel lobortis ante. Morbi tincidunt, nulla vel auctor tincidunt, ipsum magna cursus dui, at molestie justo augue id nunc.</p>

            <p>Proin mauris ante, venenatis ac lacus vel, ultrices auctor elit. Aliquam euismod congue metus, ut molestie nunc dignissim sit amet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin ut pellentesque tellus. Duis lobortis justo eu aliquet efficitur. Fusce sit amet felis ligula. Suspendisse pretium elit vel purus auctor, vel tincidunt erat consequat.</p>

            <p>Phasellus ut feugiat libero. Sed et purus metus. Integer eu est molestie, bibendum odio nec, pharetra mauris. Nullam nisl sapien, accumsan vel lacinia eu, dictum id urna. Donec sem diam, posuere sit amet lacus vel, pharetra convallis nulla. Morbi ultrices vehicula mauris, a congue lorem placerat dignissim. Pellentesque sagittis mattis euismod. Sed blandit pellentesque purus, at mollis sem venenatis in. Maecenas sed erat id velit mollis malesuada vitae vel risus. Vivamus condimentum ligula massa, at consectetur lectus fringilla id. Integer volutpat eleifend neque sed hendrerit. Vivamus laoreet eros non metus facilisis, sed efficitur purus dignissim.</p>

            <p>Etiam ut purus vitae augue varius congue id luctus augue. Sed suscipit efficitur ex a condimentum. Proin sit amet dignissim ex. Suspendisse potenti. Duis sed sem sit amet est placerat lobortis. Vivamus nunc nisi, commodo et libero sit amet, iaculis vehicula urna. Aenean erat erat, tempor ac sem non, pretium ultrices augue. Curabitur vitae rutrum lacus. Vivamus in luctus sapien. Phasellus imperdiet augue at lectus sollicitudin, eget pulvinar lacus pellentesque. Quisque quis porta tortor. Phasellus ullamcorper, nisi nec ultrices accumsan, tellus turpis sagittis nunc, quis molestie enim elit eget est.</p>
        </Base>
    )
}

export default Settings;